name: 🐛 Bug Report
description: File a bug/issue
title: "fix([SCOPE]): [TITLE]"
labels: ["bug :bug:", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Oh no! Something's not right.

        Thanks for letting us know about this bug. We appreciate your help in making our project better!

  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: Can you describe the bug and how it manifested?
      placeholder: When I try to save my user settings, an error message appears and the settings are not saved.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Please provide a clear and concise set of steps to reproduce the bug.
      render: Shell
      placeholder: |
        1. Go to the user settings page
        2. Make a change to one of the settings
        3. Click the "Save" button
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: false

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behavior
      description: What did you expect to happen when you followed the steps to reproduce the bug?
      placeholder: I expected the settings to be saved and for the page to be updated with the new settings.
    validations:
      required: false

  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual Behaviour
      description: What actually happened when you followed the steps to reproduce the bug?
      placeholder: An error message appears and the settings are not saved.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Is there any additional context or information that would be helpful in understanding and reproducing the bug?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/chill-viking/.github/blob/df12aa7d73c441721c50c89c5da96b2dc5c45bd7/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
